version: '3.8'

services:
  frontend:
    build:
      context: ./client 
      dockerfile: Dockerfile
    ports:
      - "3000:80" 
    depends_on:
      - backend

  backend:
    build:
      context: ./server 
      dockerfile: Dockerfile
    ports:
      - "3001:3001" 
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/app 
